<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Santhosh" failures="1" tests="5" name="tests.SDFCLogin" time="36.069" errors="0" timestamp="2024-05-09T09:46:28 CDT" skipped="0">
  <testcase classname="tests.SDFCLogin" name="verifyLoginErrorMessage_TC01" time="6.463"/>
  <testcase classname="tests.SDFCLogin" name="verifyLoginToSalesForce_TC02" time="8.227"/>
  <testcase classname="tests.SDFCLogin" name="ValidateLoginErrorMessage_TC4B" time="5.279"/>
  <testcase classname="tests.SDFCLogin" name="verifyRemeberMeCheckBox_TC03" time="10.266"/>
  <testcase classname="tests.SDFCLogin" name="verifyForgotPassword_TC4A" time="5.834">
    <failure message="Password reset message page is displayed. An email associated with the &lt;username&gt; account is sent. expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Password reset message page is displayed. An email associated with the <username> account is sent. expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at pages.LoginPage.verifyPasswordResetMessagePageIsDisplayed(LoginPage.java:106)
at tests.SDFCLogin.verifyForgotPassword_TC4A(SDFCLogin.java:128)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- verifyForgotPassword_TC4A -->
</testsuite> <!-- tests.SDFCLogin -->
